grafana:
  enabled: true

  additionalDataSources:
    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://tempo:3200
      editable: true

alertmanager:
  enabled: true

prometheus:
  prometheusSpec:
    retention: 7d
