apiVersion: apps/v1
kind: Deployment

metadata:
  name: orders-api
  namespace: observability

spec:
  replicas: 1

  selector:
    matchLabels:
      app: orders-api

  template:
    metadata:
      labels:
        app: orders-api

    spec:
      containers:
        - name: orders-api
          image: orders-api:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 8081

          livenessProbe:
            httpGet:
              path: /health
              port: 8081

          readinessProbe:
            httpGet:
              path: /health
              port: 8081
