apiVersion: apps/v1
kind: Deployment

metadata:
  name: orders-api
  namespace: observability

spec:
  replicas: 1

  selector:
    matchLabels:
      app: orders-api

  template:
    metadata:
      labels:
        app: orders-api

    spec:
      containers:
      - name: orders-api
        image: orders-api:v2
        imagePullPolicy: Never

        command:
          - node

        args:
          - --require
          - "@opentelemetry/auto-instrumentations-node/register"
          - app.js

        env:
          - name: OTEL_SERVICE_NAME
            value: orders-api

          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: grpc

          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://otel-collector:4317

          - name: OTEL_TRACES_EXPORTER
            value: otlp

          - name: OTEL_METRICS_EXPORTER
            value: none

        ports:
          - containerPort: 8081

        livenessProbe:
          httpGet:
            path: /health
            port: 8081

        readinessProbe:
          httpGet:
            path: /health
            port: 8081
